version: '3.8'

services:
  nginx1:
    image: nginx:alpine
    volumes:
      - ./nginx1:/usr/share/nginx/html
    networks:
      - nginx-net

  nginx2:
    image: nginx:alpine
    volumes:
      - ./nginx2:/usr/share/nginx/html
    networks:
      - nginx-net

  reverse-proxy:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    networks:
      - nginx-net

networks:
  nginx-net:
